---
title: "武汉市疫情预测分析"
subtitle: "终期报告"
author: "管晓倩 王瑶 杨洁 张莉 "
date: "2020年06月02日"
output:
  xaringan::moon_reader:
    css: [default, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---




##**3.武汉市封城市确诊患者数**

##**3.1研究背景**

##**3.2模型搭建**

##**3.3代码展示及结果**

##**3.4模型局限与展望**

##**3.5后续工作**


---

## **3.1研究背景**

&emsp;&emsp; 1.武汉2020年1月23日凌晨2时封城；
2.在封城之前，官方的确诊病例数仅是100多。但是在1月29日官方的确诊病例数已经上升到了2000例；
3.武汉市人口1100万，估计机场的人口流动量是1900万。                      


---

## **3.2模型搭建**

&nbsp;


---

&nbsp;

&emsp;&emsp;

&emsp;&emsp;

$$\dfrac{dS}{dt}=-α1*E-α2*I+σ*I$$
$$\dfrac{dE}{dt}=α1*E+α2*I-β*E$$
$$\dfrac{dI}{dt}=β*E-σ*I-γ*I$$
$$\dfrac{dD}{dt}=γ*I$$
$$\dfrac{dC}{dt}=σ*I$$
---
&nbsp;

&nbsp;

&nbsp;

&emsp;&emsp;
---

&nbsp;



&emsp;&emsp; 1.为什么设定16日为初始呢？答：16日之前的数据残缺较多，14日，15日的数据没有找到。

&emsp;&emsp; 2.为什么不用封城之前的数据？答：因为23日之前的到10日左右能找到的只有6天数据，尝试过但效果不佳，所以决定加入封城之后的数据。

&emsp;&emsp; 3.为什么数据截止到2月11日？答：因为2月12日诊断方式发生了改变，数目激增，用来估计初期的可能不太合适。

&emsp;&emsp; 4.政策措施是怎么区分的？答：当然这段时间之内多多少少存在不同强度的措施，这里只是假设一样。


---


## **3.3代码展示及结果**

```{python，echo=F}
def Binomial_log_like(n:int, p:float, k: int):
    loglik = lgamma(n+k+1) - lgamma(k+1) - lgamma(n+1) + k*np.log(p) + n*np.log(1-p)
    return loglik
```


```{python，echo=F}     
 def calculate_conf_interval(self, alpha=0.05):
        k = self.international.cases
        p = self.calculate_pro_detected_overseas()
        n_est = self.calculate_total_cases_inWuhan()
        lb = math.inf; ub = -math.inf; # initialize the original lower bound and upper bound
        for n in range(10, 100000, 10):
            LR = Binomial_log_like(n_est, p, k) - Binomial_log_like(n, p, k)
            if LR <1.92: # 95%-percentile of the Chi-square(1) distribution
                if n < lb: # the minimum value will be the lower bound
                    lb = n
                elif n> ub: # the max value is upper bound
                    ub = n  
        return (lb, ub)
``` 
---

&nbsp;
<center>表4-1时空扫描聚类结果</center>

| |基线|更小的人流量|更小的检测时间|海外病例数|海外病例数|海外病例数|海外病例数|
|:----:|:-----:|:------:|:-----:|:------:|:----:|:------:|:----:|
|海外病例数|22.470240 N, 113.886300 E|2020/1/22 to 2020/1/30|69|23.61|33.75|3.70|0.000|
|从武汉国际机场出发的每日旅客数|3301|3301|3301|3301|3301|3301|3301|
|武汉国际机场的人流量|22.470240 N, 113.886300 E|2020/1/22 to 2020/1/30|69|23.61|33.75|3.70|0.000|
|检测时间|22.470240 N, 113.886300 E|2020/1/22 to 2020/1/30|69|23.61|33.75|3.70|0.000|
|估计的总病例数|22.470240 N, 113.886300 E|2020/1/22 to 2020/1/30|69|23.61|33.75|3.70|0.000|
|估计的总病例数(95%CI)|22.470240 N, 113.886300 E|2020/1/22 to 2020/1/30|69|23.61|33.75|3.70|0.000|    
---



---



## **3.4模型局限与展望**

&emsp;&emsp;1.α具体的值是模型基于已有数据拟合出来的,模型中感染率为常数；

&emsp;&emsp;2.实际上，随着病毒感染的人越来越多，这导致易感人群逐渐减少，实际上R0是会在远期下降的。也就是说，每期新增感染人数应该是一个与易感人群规模、潜伏者和确诊患者的函数。而此模型中，由于在感染初期，武汉市的人口规模并不会成为病毒感染的显著限制之一，所以定义的新增感染人数与易感人群规模无关。

&emsp;&emsp;3.可以把模型的新增患者数修改为一个动态的函数，许多研究已经包含此相关的内容可以进行借鉴。在疫情发展的初期、中期、后期和末期分别拟合模型估计分阶段R0。


---

## **3.5后续工作**

&emsp;&emsp;使用海外检测到的病例数来估计在封城之前在武汉可能发生的病例。现有背景如下：

&emsp;&emsp; 1.武汉封闭时间:1月23日凌晨2点;

&emsp;&emsp; 2.武汉的官方确诊病例在关闭前刚刚超过100例，在1月29日上升到2000例;

&emsp;&emsp; 3.根据2019年的交通数据估计机场人数。

---
